### ISSUE TITLE
Working But Bug 

### ISSUE THREAD

**Issue by DevSupportiVe** [Pr0t0ns/Pr0t0n-X-ADylan-Token-Creator-Joiner#2]
https://prnt.sc/tNCR6ESbJZhC

Proxies Working Well , Ai Solver Working And Solving But Joiner Not Joining Tokens After Process Is Done , Also Should Make It To Where Tokens That Get Created Get Put In A Tokens.txt

**Comment by Pr0t0ns** [comment]
You need to put only the code not the whole invite link

**Comment by DevSupportiVe** [comment]
> You need to put only the code not the whole invite link
https://prnt.sc/4nBwQY1A5jyT
