### ISSUE TITLE
Ai Solver Not Working

### ISSUE THREAD

**Issue by HonchoGz** [Pr0t0ns/Pr0t0n-X-ADylan-Token-Creator-Joiner#3]
![Screenshot_1](https://user-images.githubusercontent.com/28749238/182002709-7f03f4ad-f0c6-4055-b5b7-f33a05135e5e.png)

**Comment by lkeld** [comment]
It does work, just the amount of people / load on the server can crash it at times. It is suggested to lower your thread count or wait for the website to start working again.

**Comment by Pr0t0ns** [comment]
^^
